# Site settings
title: Artists Theme
description: Thinker // Designer // YouTuber
email: artist@email



# Change the site default images and content here!
logo: logo.svg
bg-img: hero-bg.jpg

avatar: travitar.jpg
blurb: <p><strong>Travis specializes in making things</strong> for human people. Most of the things he makes are <a href="https://travisneilson.com">digital interfaces</a>, but he also puts effort into crafting <a href="https://soundcloud.com/travis-neilson">next-level beats</a> and <a href="http://youtube.com/user/devtipsfordesigners">YouTube videos</a> about making codes happen.</p>


# Build settings
markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested
